name: test

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: node:14.19.0-alpine
    steps:
      - name: Install git
        run: apk --update add git tar
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}-v4
      - name: Install dependencies
        run: npm ci --ignore-scripts
  eslint:
    needs: build
    name: ESLint
    runs-on: ubuntu-latest
    container:
      image: node:14.19.0-alpine
    steps:
      - name: Install git
        run: apk --update add git tar
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}-v4
      - name: Lint source code with ESLint
        run: npm run lint
  prettier:
    needs: build
    name: Prettier
    runs-on: ubuntu-latest
    container:
      image: node:14.19.0-alpine
    steps:
      - name: Install git
        run: apk --update add git tar
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}-v4
      - name: Lint source code with Prettier
        run: npm run check:format
